version = 0.1
[hello-world-sam]
[hello-world-sam.deploy]
[hello-world-sam.deploy.parameters]
stack_name = "hello-world-sam"
s3_bucket = "pandey-sam"
s3_prefix = "hello-world-sam"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
